### ISSUE TITLE
When fetching resources with a URL, the URL is hit too many times

### ISSUE THREAD

**Issue by jsgoupil** [seankenny/fullcalendar#38]
The method `buildDayTableHeadHTML` uses code like this:
`var resource = resources()[col];`
which loops over each columns.

This makes a call per column to the server.

**Comment by seankenny** [comment]
Hi - the resources() function (referenced to fetchResources() in ResourcesManager.js) makes use of a cache flag in order to cache after the first resources are fetched.  This would/should prevent multiple http calls from occurring.  Are you seeing multiple http calls?  If so, can you provide a http://plnkr.co/ example of what you are seeing?

Thanks!

**Comment by jsgoupil** [comment]
Here...
43 requests:
http://plnkr.co/edit/VbiFmWOuRct38m1WN7El?p=info
